apiVersion: v2
name: pifanctl-operator
description: Declarative Raspberry Pi fan topology and node-bound PWM workers
type: application
version: 1.2.1
appVersion: "1.2.1"
home: https://github.com/jyje/pifanctl
