apiVersion: apps/v1
kind: Deployment
metadata:
  name: pifanctl
spec:
  selector:
    matchLabels:
      app: pifanctl
  template:
    metadata:
      labels:
        app: pifanctl
    spec:
      containers:
      - name: main
        image: ghcr.io/jyje/pifanctl:latest
        command: ["python", "main.py", "start"]
        env:
        - name: PIN
          value: "18"
        - name: LOG_LEVEL
          value: INFO
        - name: PWM_REFRESH_INTERVAL
          value: "30"
        - name: TARGET_TEMPERATURE
          value: "50"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        securityContext:
          privileged: true
      # tolerations:
      #   - key: node-role.kubernetes.io/control-plane
      #     operator: Exists
      #     effect: NoSchedule
      # nodeSelector:
      #   kubernetes.io/hostname: raspi-40 # change to your own hostname
